version: "3"
services:
  database:
    image: mysql:5.7
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
      - "--sql-mode="
    ports:
      - "3306:3306"
    restart: on-failure:5
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: wordpress

  wordpress:
    depends_on:
      - database
    image: wordpress:php7.4
    ports:
      - "80:80"
    restart: on-failure:5
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: "database"
      WORDPRESS_DB_PASSWORD: "secret"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_NAME: "wordpress"